# Generated by Django 6.0.2 on 2026-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0003_matchresilt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchResilt',
            new_name='MatchResult',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
